sudo: true
language: c
install:
  - "yes | sudo add-apt-repository ppa:snaipewastaken/ppa"
  - sudo apt-get update
  - sudo apt-get install criterion

script:
  - make normal test
  - bin/test_yacbnl
  - make CMD_ARGS=-DPREFER_CHAR_CONV
  - bin/test_yacbnl

